INSERT INTO tb_sorteios (data_sorteio) VALUES (TIMESTAMP WITH TIME ZONE '2021-04-13T20:50:07.12345Z');
INSERT INTO tb_sorteios (data_sorteio) VALUES (TIMESTAMP WITH TIME ZONE '2021-02-03T12:50:07.12345Z');
INSERT INTO tb_sorteios (data_sorteio) VALUES (TIMESTAMP WITH TIME ZONE '2021-06-13T20:50:07.12345Z');

INSERT INTO tb_jogadores (email, name) VALUES ('elisa@gmail.com', 'Elisa Silva');
INSERT INTO tb_jogadores (email, name) VALUES ('leila@gmail.com', 'Leila Dias');
INSERT INTO tb_jogadores (email, name) VALUES ('andre@gmail.com', 'Andre Fonseca');
INSERT INTO tb_jogadores (email, name) VALUES ('marcio@gmail.com', 'Marcio afonso');

INSERT INTO tb_bilhetes (data_aposta, numero_sorteio, jogador_id) VALUES (NOW(),1, 1 );
INSERT INTO tb_bilhetes (data_aposta, numero_sorteio, jogador_id) VALUES (NOW(),1, 2 );
INSERT INTO tb_bilhetes (data_aposta, numero_sorteio, jogador_id) VALUES (NOW(),1, 3 );
INSERT INTO tb_bilhetes (data_aposta, numero_sorteio, jogador_id) VALUES (NOW(),1, 4 );
INSERT INTO tb_bilhetes (data_aposta, numero_sorteio, jogador_id) VALUES (NOW(),1, 1 );
INSERT INTO tb_bilhetes (data_aposta, numero_sorteio, jogador_id) VALUES (NOW(),1, 1 );
INSERT INTO tb_bilhetes (data_aposta, numero_sorteio, jogador_id) VALUES (NOW(),1, 2 );
INSERT INTO tb_bilhetes (data_aposta, numero_sorteio, jogador_id) VALUES (NOW(),1, 3 );
INSERT INTO tb_bilhetes (data_aposta, numero_sorteio, jogador_id) VALUES (NOW(),1, 4 );

INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (1, 31);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (1, 32);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (1, 44);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (1, 33);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (1, 18);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (1, 17);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (2, 16);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (2, 15);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (2, 13);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (2, 14);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (2, 12);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (2, 33);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (3, 44);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (3, 41);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (3, 33);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (3, 28);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (3, 27);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (3, 26);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (4, 25);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (4, 24);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (4, 23);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (4, 22);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (4, 21);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (4, 33);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (5, 58);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (5, 57);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (5, 56);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (5, 55);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (5, 33);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (5, 50);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (6, 44);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (6, 43);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (6, 41);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (6, 35);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (6, 38);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (6, 37);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (7, 31);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (7, 55);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (7, 42);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (7, 54);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (7, 33);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (7, 43);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (8, 34);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (8, 23);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (8, 32);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (8, 12);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (8, 21);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (8, 33);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (9, 6);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (9, 5);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (9, 4);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (9, 3);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (9, 2);
INSERT INTO bilhete_numeros (bilhete_id, numeros) VALUES (9, 1);

INSERT INTO sorteio_numeros_sorteados (sorteio_id, numeros_sorteados) VALUES (1, 6);
INSERT INTO sorteio_numeros_sorteados (sorteio_id, numeros_sorteados) VALUES (1, 5);
INSERT INTO sorteio_numeros_sorteados (sorteio_id, numeros_sorteados) VALUES (1, 4);
INSERT INTO sorteio_numeros_sorteados (sorteio_id, numeros_sorteados) VALUES (1, 3);
INSERT INTO sorteio_numeros_sorteados (sorteio_id, numeros_sorteados) VALUES (1, 2);
INSERT INTO sorteio_numeros_sorteados (sorteio_id, numeros_sorteados) VALUES (1, 1);


